const allCountries = [
	["Afghanistan", "Kabul", "Asia", "af"],
	["Albania", "Tirana", "Europe", "al"],
	["Algeria", "Algiers", "Africa", "dz"],
	["Andorra", "Andorra la Vella", "Europe", "ad"],
	["Antigua and Barbuda", "St. Johns", "America", "ag"],
	["Argentina", "Buenos Aires", "America", "ar"],
	["Armenia", "Yerevan", "Asia", "am"],
	["Australia", "Canberra", "Oceania", "au"],
	["Austria", "Vienna", "Europe", "at"],
	["Azerbaijan", "Baku", "Asia", "az"],
	["Bahamas", "Nassau", "America", "bs"],
	["Bahrain", "Manama", "Asia", "bh"],
	["Bangladesh", "Dhaka", "Asia", "bd"],
	["Barbados", "Bridgetown", "America", "bb"],
	["Belarus", "Minsk", "Europe", "by"],
	["Belgium", "Brussels", "Europe", "be"],
	["Belize", "Belmopan", "America", "bz"],
	["Benin", "Porto Novo", "Africa", "bj"],
	["Bhutan", "Thimphu", "Asia", "bt"],
	["Bolivia", "Sucre", "America", "bo"],
	["Bosnia and Herzegovina", "Sarajevo", "Europe", "ba"],
	["Botswana", "Gaborone", "Africa", "bw"],
	["Brazil", "Brasilia", "America", "br"],
	["Brunei", "Bandar Seri Begawan", "Asia", "bn"],
	["Bulgaria", "Sofia", "Europe", "bg"],
	["Burkina Faso", "Ouagadougou", "Africa", "bf"],
	["Burundi", "Bujumbura", "Africa", "bi"],
	["Cambodia", "Phnom Penh", "Asia", "kh"],
	["Cameroon", "Yaoundé", "Africa", "cm"],
	["Canada", "Ottawa", "America", "ca"],
	["Cape Verde", "Praia", "Africa", "cv"],
	["Central African Republic", "Bangui", "Africa", "cf"],
	["Chad", "N Djamena", "Africa", "td"],
	["Chile", "Santiago", "America", "cl"],
	["China", "Beijing", "Asia", "cn"],
	["Colombia", "Bogota", "America", "co"],
	["Comoros", "Moroni", "Africa", "km"],
	["Costa Rica", "San José", "America", "cr"],
	["Croatia", "Zagreb", "Europe", "hr"],
	["Cuba", "Havana", "America", "cu"],
	["Cyprus", "Nicosia", "Europe", "cy"],
	["Czech Republic", "Prague", "Europe", "cz"],
	["Democratic Republic of Congo", "Kinshasa", "Africa", "cd"],
	["Denmark", "Copenagen", "Europe", "dk"],
	["Djibouti", "Djibouti", "Africa", "dj"],
	["Dominica", "Roseau", "America", "dm"],
	["Dominican Republic", "Santo Domingo", "America", "do"],
	["East Timor", "Dili", "Oceania", "tl"],
	["Ecuador", "Quito", "America", "ec"],
	["Egypt", "Cairo", "Africa", "eg"],
	["El Salvador", "San Salvador", "America", "sv"],
	["Equatorial Guinea", "Malabo", "Africa", "gq"],
	["Eritrea", "Asmara", "Africa", "er"],
	["Estonia", "Tallinn", "Europe", "ee"],
	["Eswatini", "Mbabane", "Africa", "sz"],
	["Ethiopia", "Addis Ababa", "Africa", "et"],
	["Fiji", "Suva", "Oceania", "fj"],
	["Finland", "Helsinki", "Europe", "fi"],
	["France", "Paris", "Europe", "fr"],
	["Gabon", "Libreville", "Africa", "ga"],
	["Gambia", "Banjul", "Africa", "gm"],
	["Georgia", "Tbilisi", "Asia", "ge"],
	["Germany", "Berlin", "Europe", "de"],
	["Ghana", "Accra", "Africa", "gh"],
	["Greece", "Athens", "Europe", "gr"],
	["Grenada", "St. George's", "America", "gd"],
	["Guatemala", "Guatemala City", "America", "gt"],
	["Guinea", "Conakry", "Africa", "gn"],
	["Guinea-Bissau", "Bissau", "Africa", "gw"],
	["Guyana", "Georgetown", "America", "gy"],
	["Haiti", "Port-au-Prince", "America", "ht"],
	["Honduras", "Tegucigalpa", "America", "hn"],
	["Hungary", "Budapest", "Europe", "hu"],
	["Iceland", "Reykjavík", "Europe", "is"],
	["India", "New Delhi", "Asia", "in"],
	["Indonesia", "Jakarta", "Asia", "id"],
	["Iran", "Tehran", "Asia", "ir"],
	["Iraq", "Baghdad", "Asia", "iq"],
	["Ireland", "Dublin", "Europe", "ie"],
	["Israel", "Jerusalem", "Asia", "il"],
	["Italy", "Rome", "Europe", "it"],
	["Ivory Coast", "Yamoussoukro", "Africa", "ci"],
	["Jamaica", "Kingston", "America", "jm"],
	["Japan", "Tokyo", "Asia", "jp"],
	["Jordan", "Amman", "Asia", "jo"],
	["Kazakhstan", "Astana", "Asia", "kz"],
	["Kenya", "Nairobi", "Africa", "ke"],
	["Kiribati", "Tarawa", "Oceania", "ki"],
	["North Korea", "Pyongyang", "Asia", "kp"],
	["South Korea", "Seoul", "Asia", "kp"],
	["Kosovo", "Pristina", "Europe", "xk"],
	["Kuwait", "Kuwait City", "Asia", "kw"],
	["Kyrgyzstan", "Bishkek", "Asia", "kg"],
	["Laos", "Vientiane", "Asia", "la"],
	["Latvia", "Riga", "Europe", "lv"],
	["Lebanon", "Beirut", "Asia", "lb"],
	["Lesotho", "Maseru", "Africa", "ls"],
	["Liberia", "Monrovia", "Africa", "lr"],
	["Libya", "Tripoli", "Africa", "ly"],
	["Liechtenstein", "Vaduz", "Europe", "li"],
	["Lithuania", "Vilnius", "Europe", "lt"],
	["Luxembourg", "Luxembourg", "Europe", "lu"],
	["Madagascar", "Antananarivo", "Africa", "mg"],
	["Malawi", "Lilongwe", "Africa", "mw"],
	["Malaysia", "Kuala Lumpur", "Asia", "my"],
	["Maldives", "Malé", "Asia", "mv"],
	["Mali", "Bamako", "Africa", "ml"],
	["Malta", "Valletta", "Europe", "mt"],
	["Marshall Islands", "Majuro", "Oceania", "mh"],
	["Mauritania", "Nouakchott", "Africa", "mr"],
	["Mauritius", "Port Louis", "Africa", "mu"],
	["Mexico", "Mexico City", "America", "mx"],
	["Micronesia", "Palikir", "Oceania", "fm"],
	["Moldova", "Chisinau", "Europe", "md"],
	["Monaco", "Monaco", "Europe", "mc"],
	["Mongolia", "Ulaanbaatar", "Asia", "mn"],
	["Montenegro", "Podgorica", "Europe", "me"],
	["Morocco", "Rabat", "Africa", "ma"],
	["Mozambique", "Maputo", "Africa", "mz"],
	["Myanmar", "Naypyidaw", "Asia", "mm"],
	["Namibia", "Windhoek", "Africa", "na"],
	["Nauru", "Yaren", "Oceania", "nr"],
	["Nepal", "Kathmandu", "Asia", "np"],
	["Netherlands", "Amsterdam", "Europe", "nl"],
	["New Zealand", "Wellington", "Oceania", "nz"],
	["Nicaragua", "Managua", "America", "ni"],
	["Niger", "Niamey", "Africa", "ne"],
	["Nigeria", "Abuja", "Africa", "ng"],
	["North Macedonia", "Skopje", "Europe", "mk"],
	["Norway", "Oslo", "Europe", "no"],
	["Oman", "Muscat", "Asia", "om"],
	["Pakistan", "Islamabad", "Asia", "pk"],
	["Palau", "Melekeok", "Oceania", "pw"],
	["Palestine", "East Jerusalem", "Asia", "ps"],
	["Panama", "Panama City", "America", "pa"],
	["Papua New Guinea", "Port Moresby", "Oceania", "pg"],
	["Paraguay", "Asunción", "America", "py"],
	["Peru", "Lima", "America", "pe"],
	["Philippines", "Manila", "Asia", "ph"],
	["Poland", "Warsaw", "Europe", "pl"],
	["Portugal", "Lisbon", "Europe", "pt"],
	["Qatar", "Doha", "Asia", "qa"],
	["Republic of the Congo", "Brazzaville", "Africa", "cg"],
	["Romania", "Bucharest", "Europe", "ro"],
	["Russia", "Moscow", "Europe", "ru"],
	["Rwanda", "Kigali", "Africa", "rw"],
	["Saint Kitts and Nevis", "Basseterre", "America", "kn"],
	["Saint Lucia", "Castries", "America", "lc"],
	["Saint Vincent and the Grenadines", "Kingstown", "America", "vc"],
	["Samoa", "Apia", "Oceania", "ws"],
	["San Marino", "San Marino", "Europe", "sm"],
	["São Tomé and Príncipe", "São Tomé", "Africa", "st"],
	["Saudi Arabia", "Riyadh", "Asia", "sa"],
	["Senegal", "Dakar", "Africa", "sn"],
	["Serbia", "Belgrade", "Europe", "rs"],
	["Seychelles", "Victoria", "Africa", "sc"],
	["Sierra Leone", "Freetown", "Africa", "sl"],
	["Singapore", "Singapore", "Asia", "sg"],
	["Slovakia", "Bratislava", "Europe", "sk"],
	["Slovenia", "Ljubljana", "Europe", "si"],
	["Solomon Islands", "Honiara", "Oceania", "sb"],
	["Somalia", "Mogadishu", "Africa", "so"],
	["South Africa", "Pretoria", "Africa", "za"],
	["South Sudan", "Juba", "Africa", "ss"],
	["Spain", "Madrid", "Europe", "es"],
	["Sri Lanka", "Sri Jayawardenapura Kotte", "Asia", "lk"],
	["Sudan", "Khartoum", "Africa", "sd"],
	["Suriname", "Paramaribo", "America", "sr"],
	["Sweden", "Stockholm", "Europe", "se"],
	["Switzerland", "Bern", "Europe", "ch"],
	["Syria", "Damascus", "Asia", "sy"],
	["Taiwan", "Taipei", "Asia", "tw"],
	["Tajikistan", "Dushanbe", "Asia", "tj"],
	["Tanzania", "Dodoma", "Africa", "tz"],
	["Thailand", "Bangkok", "Asia", "th"],
	["Togo", "Lomé", "Africa", "tg"],
	["Tonga", "Nukualofa", "Oceania", "to"],
	["Trinidad and Tobago", "Port of Spain", "America", "tt"],
	["Tunisia", "Tunis", "Africa", "tn"],
	["Turkey", "Ankara", "Asia", "tr"],
	["Turkmenistan", "Ashgabat", "Asia", "tm"],
	["Tuvalu", "Funafuti", "Oceania", "tv"],
	["Uganda", "Kampala", "Africa", "ug"],
	["Ukraine", "Kiev", "Europe", "ua"],
	["United Arab Emirates", "Abu Dhabi", "Asia", "ae"],
	["United Kingdom", "London", "Europe", "gb"],
	["United States", "Washington D.C.", "America", "us"],
	["Uruguay", "Montevideo", "America", "uy"],
	["Uzbekistan", "Tashkent", "Asia", "uz"],
	["Vanuatu", "Port Vila", "Oceania", "vu"],
	["Vatican City", "Vatican City", "Europe", "va"],
	["Venezuela", "Caracas", "America", "ve"],
	["Vietnam", "Hanoi", "Asia", "vn"],
	["Yemen", "Sana'a", "Asia", "ye"],
	["Zambia", "Lusaka", "Africa", "zm"],
	["Zimbabwe", "Harare", "Africa", "zw"],
];


export { allCountries };